// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5

package handler

import (
	"net/http"

	photo "server/internal/handler/photo"
	"server/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/order/delete",
				Handler: photo.DeleteOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/order/info",
				Handler: photo.OrderInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/order/list",
				Handler: photo.OrderListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/order/submit",
				Handler: photo.SubmitHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/order/update_status",
				Handler: photo.UpdateOrderStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/photo/upload",
				Handler: photo.UploadHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/ping",
				Handler: photo.PingHandler(serverCtx),
			},
		},
	)
}
