// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5

package handler

import (
	"net/http"

	admin "server/internal/handler/admin"
	api "server/internal/handler/api"
	"server/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/admin/order/delete",
				Handler: admin.AdminOrderDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/admin/order/info",
				Handler: admin.AdminOrderInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/admin/order/list",
				Handler: admin.AdminOrderListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/admin/order/update_status",
				Handler: admin.AdminOrderUpdateStatusHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/order/info",
				Handler: api.OrderInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/order/submit",
				Handler: api.SubmitHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/photo/upload",
				Handler: api.UploadHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/ping",
				Handler: api.PingHandler(serverCtx),
			},
		},
	)
}
