// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package handler

import (
	"net/http"

	"photo-kits-server/server/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/photo/submit",
				Handler: SubmitHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/photo/upload",
				Handler: UploadHandler(serverCtx),
			},
		},
	)
}
