// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type DownloadRequest struct {
	File string `json:"file"`
}

type Photo struct {
	Size int64    `json:"size"`
	Unit string   `json:"unit"`
	Urls []string `json:"urls"`
}

type SubmitRequest struct {
	OrderSn  string  `json:"filename"`
	Receiver int64   `json:"receiver"`
	Remark   string  `json:"remark"`
	Photos   []Photo `json:"photo"`
}

type UploadResponse struct {
	Filename string `json:"filename"`
	Size     int64  `json:"size"`
	Sha1     string `json:"sha1"`
	URL      string `json:"url"`
}
