// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type DownloadRequest struct {
	File string `json:"file"`
}

type UploadResponse struct {
	Filename string `json:"filename"`
	Size     int64  `json:"size"`
	Sha1     string `json:"sha1"`
	URL      string `json:"url"`
}
