// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type OrderDeleteRequest struct {
	OrderIds []int64 `json:"order_id"`
}

type OrderDeleteResponse struct {
	Total int64 `json:"total"` // 删除了多少个
}

type OrderInfoRequest struct {
	OrderSn string `json:"order_sn"`
}

type OrderInfoResponse struct {
	OrderSn   string  `json:"order_sn"`
	Receiver  string  `json:"receiver"`
	Remark    string  `json:"remark"`
	Status    int64   `json:"status"`
	CreatedAt string  `json:"created_at"`
	Photos    []Photo `json:"photos"`
}

type OrderItem struct {
	ID        int64  `json:"id"`
	OrderSn   string `json:"order_sn"`
	Receiver  string `json:"receiver"`
	Status    int64  `json:"status"`
	CreatedAt string `json:"created_at"`
}

type OrderListRequest struct {
	OrderSn   string `form:"order_sn,optional"`
	Receiver  string `form:"receiver,optional"`
	Remark    string `form:"remark,optional"`
	Status    int64  `form:"status,optional"`
	CreatedAt string `form:"created_at,optional"`
	Page      int64  `form:"page,optional"`
	PageSize  int64  `form:"page_size,optional"`
}

type OrderListResponse struct {
	List     []OrderItem `json:"list"`
	Total    int64       `json:"total"`
	Page     int64       `json:"page"`
	PageSize int64       `json:"page_size"`
	Pages    int64       `json:"pages"`
}

type OrderUpdateStatusRequest struct {
	OrderId []int64 `json:"order_id"`
	Status  int64   `json:"status"`
}

type OrderUpdateStatusResponse struct {
	Total int64 `json:"total"` // 更新了多少个
}

type Photo struct {
	Spec     string          `json:"spec"`
	Metadata []PhotoMetadata `json:"metadata"`
}

type PhotoMetadata struct {
	URL       string `json:"url"`
	IsResized int64  `json:"is_resized"`
}

type SubmitRequest struct {
	OrderSn    string  `json:"order_sn"`
	Receiver   string  `json:"receiver"`
	Remark     string  `json:"remark"`
	PhotoCount int64   `json:"photo_count,optional"`
	Photos     []Photo `json:"photos"`
}

type SubmitResponse struct {
	Total int64 `json:"total"`
}

type UploadResponse struct {
	Filename string `json:"filename"`
	Size     int64  `json:"size"`
	Sha1     string `json:"sha1"`
	URL      string `json:"url"`
}
